### ISSUE TITLE
Heavy Lag when jumping trough star gates and docking.

### ISSUE THREAD

**Issue by drpetarvojvodic** [ISeeDEDPpl/Questor#56] opened 2012-04-20 13:32 UTC
When doing manual jump or docking procedure it's normal, but when questor is jumping it has 3-4 seconds of extreme lag and choppiness. Don't know what is the cause but i think if is worth to report especially if it any way it can be seen in the ccp logs

**Comment by ISeeDEDPpl** [comment] 2012-04-20 14:31
If their anything in your gamelog that corresponds to this? 

You can also bring up the 'in game' logserver - ctrl-alt-shift m
then goto the rightmost tab and look there for any errors that may line up time wise with the lag you are seeing at gates. 

Does the client not lag at gates without questor running?

**Comment by drpetarvojvodic** [comment] 2012-04-20 18:56
The client acts normal when not running questor. No lag docking or jumping. Game-log also doesn't show anything strange happening. I was looking at the logserver and there is a lot of stuff there, errors and warning's, but couldn't figure out if any of it has anything to do with the lag i have. I'm going to continue looking and hopefully figure it out. I also noticed in the debugger log that besides "panic state: normal" (like it used to until recently)  there is also a constant occurrence of "savager trying to target wrecks", and even "try to loot" right after jumping to the pocket and if i remember correctly star gate too. it seems to be stuck in this state constantly. The ship acts normally and does all the actions correctly nevertheless. Don't know if it is important or not but thot i mention it here rather than opening new conversation.

**Comment by ISeeDEDPpl** [comment] 2012-04-21 20:09
it might be helpful to turn on:
 `
  <debugStates>true</debugStates>  
  
  <debugPerformance>true</debugPerformance>  `

and see if their is anything gleaned in the logs

**Comment by xelj** [comment] 2012-04-25 20:21
Same problem, 3-4sec lag when jumping, docking or initial warp

**Comment by ghost** [comment] 2012-04-26 21:00
Same problem, when you manually change state from most any mission running state to goto base (not delayed goto base) it will lag like fuck with approach spam, which had an appempted fix, still it lags, and after the mission is done it will lag, i think you need to put a timer in for it to wait AFTER setting the location to warp to then warping, not all at the same time, and the approach spam needs to be fixed.

**Comment by ISeeDEDPpl** [comment] 2012-04-26 21:45
Dim, can you give an example console log of that pls?

**Comment by ISeeDEDPpl** [comment] 2012-04-26 22:45
This will be much easier to debug and resolve after the questor restructuring is complete next week sometime.  This issue will have to wait until then unless someone else tackles it before then.

**Comment by ISeeDEDPpl** [comment] 2012-05-02 08:13
ok, this is confirmed to be an issue. It "seems" to be an issue whenever the traveler is engaged. Can anyone confirm that it is _everytime_ we switch traveler into gear? that would cover gotobase. gotomission and gotobookmark (for after mission salvaging)... Im still not sure what the issue is but having someplace to concentrate the search is good =/

**Comment by drpetarvojvodic** [comment] 2012-05-02 08:24
your probably right about that. Lag hits when setting up a travel destination while in space (ma by even in station but i cant tell with all effects off), jumping gates, docking stations. It look's like a traveler problem. Keep up the good work, what our done so far is amazing.

**Comment by ISeeDEDPpl** [comment] 2012-05-03 09:43
can someone test this with the restructuring branch please? I optimized traveler quite a bit and it should be quite a bit better. If needed I can likely optimize a bit more, but Id like to avoid extra work if unnecessary. Travler is working, but I wasnt paying much attention to the lag situation when starting traveler (gotobase or gotomission)

**Comment by drpetarvojvodic** [comment] 2012-05-04 06:50
I just tried out the restructuring branch (just compiled questor) and unfortunately it still has that 3-4 lag hiccups when doing above already discussed actions. Also during the test's i had a situation that it will try to unload loot while in space And every time it need's to jump and warp it will try and orbit "the system itself" not the gate or anything else but the system hes in, or it just log's it like that (i'm talking about restructured branch) . Aldo great job on all the new setting's it's going to be great once complete!

08:09:00 CombatMissionsBehavior: GotoBase: initiating Orbit of [y7-hfd] orbiting at [0]
08:09:01 CombatMissionsBehavior: UnloadLoot: Begin
-here i stooped it and tried the go to base option again-
08:09:18 CombatMissionsBehavior: Heading back to base
08:09:19 CombatMissionsBehavior: GotoBase: initiating Orbit of [y7-hfd] orbiting at [0]
08:09:20 TravelerDestination.StationDestination: Destination set to [uer-th V - Moon 2 station]
08:09:21 Traveler: Setting destination to [uer-th]

**Comment by ghost** [comment] 2012-05-04 16:45
I'm still getting heavy lag at gates even with a natural goto base state change. (every once and a while)

**Comment by ISeeDEDPpl** [comment] 2012-05-04 17:40
C-pak, the name above "y7-hfd" is the name of the gate. They removed 'stargate' from the name of the entity. 
Why the hell it would be orbiting at 0 is another question altogether. 

As far as unloadloot it sounds like you accidentally changed the unloadloot state in the states tab. 
Unloadloot should also be checking to amke sure it is in station before doing ANY processing.

In ProcessState
`
            if (!Cache.Instance.InStation)
                return;
`
`
            if (Cache.Instance.InSpace)
                return;
`

**Comment by ISeeDEDPpl** [comment] 2012-05-04 17:52
The orbit issue has been fixed, it was just a logging problem. the actual orbit was not at 0k.

**Comment by drpetarvojvodic** [comment] 2012-05-04 18:20
Ahh ok, i forgot the gate names change. Dow i still think initiating orbit at the gate right before jumping is a bit odd to do. 
I'm still testing, will report if i find something that can point to the lag cause.

**Comment by ISeeDEDPpl** [comment] 2012-05-06 06:18
I removed stargates from the list of objects we dont want to be close to. That should fix the orbiting before jumping. It DOES however create a situation where if we are at the keyboard and switch states from gotomission to gotobase or vice versa, that we could very well get caught on the gate. Hopefully with someone at the keyboard they would notice this.

**Comment by ISeeDEDPpl** [comment] 2012-05-09 13:01
In the name of science can someone test if this symptom is in da-teach's master and or experimental and report back here please?

**Comment by drpetarvojvodic** [comment] 2012-05-09 20:48
I'll give it a go and report what i got.

**Comment by ISeeDEDPpl** [comment] 2012-06-28 03:54
if this is happening in the da-teach\unstable branch as well you may want to report it to Ganondorf, he may have some additional ideas. I am at a loss. It occurs when loading the traveler (seemingly)... not sure exactly why without more debugging. My intrest level is fairly low because the 'lag' doesnt cause any side effects for me, just a few seconds of laggyness / unresponsiveness / framerate drop.

**Comment by ghost** [comment] 2012-07-06 07:53
I think its because questor does 2 things at the same time when it decides its finished with a mission... select the warp destination and warp all on the same frame... if you put a delay in that then maybe the lag would stop... just my thought.

**Comment by ISeeDEDPpl** [comment] 2012-07-10 04:20
this has been resolved in latest experimental.

**Closed as completed by ISeeDEDPpl** 2012-07-10 04:20 UTC
