### ISSUE TITLE
ISDP - Bleeding - 0b347f37b9 - 7.2 Apr 2013 

### ISSUE THREAD

**Issue by Pluckyduck** [ISeeDEDPpl/Questor#356] opened 2013-04-07 22:53 UTC
told to kill Federation Praktor Magister and then got sensor to death....and just went to try to activate missiles on it with out being locked...

Pastebin ( http://pastebin.com/MYvn00kR ) 

or

09:44:44 [Cache.SetmissionXmlPath] [C:\Program Files (x86)\InnerSpace.NET Programs\Caldari L3 Missions\Driving a Wedge - Consulate Conflagration (2 of 2).xml] found!
09:44:44 [Cache] Using Settings Orbit distance [5000]
09:44:44 [Cache] Using Settings OptimalRange [0]
09:44:44 [-] -----------------------------------------------------------------
09:44:44 [-] -----------------------------------------------------------------
09:44:44 [CombatMissionCtrl] Mission Timer Currently At: [46] min
09:44:44 [CombatMissionCtrl] Max Range is currently: 53k
09:44:44 [-] -----------------------------------------------------------------
09:44:44 [-] -----------------------------------------------------------------
09:44:44 [CombatMissionCtrl] Pocket [0] loaded, executing the following actions
09:44:44 [CombatMissionCtrl] Action [ 1 ] Kill [target: Federation Praktor Magister]
09:44:44 [CombatMissionCtrl] Action [ 2 ] Done
09:44:44 [-] -----------------------------------------------------------------
09:44:44 [-] -----------------------------------------------------------------
09:44:44 [Statistics.ObjectStatistics] Logging info on the [32] objects in this pocket to [C:\Program Files (x86)\InnerSpace.NET Programs\log_MyEVECharacterNameRedacted_\PocketObjectStats_MyEVECharacterNameRedacted_ - Driving a Wedge - Consulate Conflagration (2 of 2) - 0 - ObjectStatistics.csv]
09:44:45 [Panic] Adding [Federation Praktor Magister] Speed [0.06k/s] Distance [35.01842] [ID: [truncatedID]56238] as a PrimaryWeaponPriorityTarget
09:44:46 [Combat] Targeting priority target [Federation Praktor Magister][ID: [truncatedID]56238][35k away] highValueTargets.Count [0]
09:44:47 [Combat] Activating weapon [1] on [Federation Praktor Magister][ID: [truncatedID]56238][35k away]
09:44:47 [Salvage] Stacking CargoHold: waiting [-2764sec]
09:44:47 [Salvage] Done stacking
09:44:49 [Combat] Activating weapon [1] on [Federation Praktor Magister][ID: [truncatedID]56238][35k away]
09:44:56 [Combat] Activating weapon [1] on [Federation Praktor Magister][ID: [truncatedID]56238][35k away]
09:44:57 [Panic] Adding [Elite Federation Insidiator] Speed [0.02k/s] Distance [28.90852] [ID: [truncatedID]39555] as a PrimaryWeaponPriorityTarget
09:44:57 [Panic] Adding [Elite Federation Insidiator] Speed [0.02k/s] Distance [28.3615] [ID: [truncatedID]56226] as a PrimaryWeaponPriorityTarget
09:44:57 [Panic] Adding [Elite Federation Insidiator] Speed [0.02k/s] Distance [25.83769] [ID: [truncatedID]39562] as a PrimaryWeaponPriorityTarget
09:44:57 [Combat] Unlocking Target [Federation Praktor Magister][ID: [truncatedID]56238] out of range [35k away] It will be relocked when it comes back into range. [21.82]
09:45:02 [Combat] Activating weapon [1] on [Federation Praktor Magister][ID: [truncatedID]56238][35k away]
09:45:07 [Combat] Targeting priority target [Federation Praktor Magister][ID: [truncatedID]56238][35k away] highValueTargets.Count [0]
09:45:08 [Combat] Activating weapon [1] on [Federation Praktor Magister][ID: [truncatedID]56238][35k away]
09:45:09 [Combat] Targeting priority target [Elite Federation Insidiator][ID: [truncatedID]39562][23k away] highValueTargets.Count [1]
09:45:12 [Combat] Targeting priority target [Elite Federation Insidiator][ID: [truncatedID]56226][25k away] highValueTargets.Count [2]
09:45:14 [Combat] Targeting priority target [Elite Federation Insidiator][ID: [truncatedID]39555][26k away] highValueTargets.Count [3]
09:45:15 [Combat] Activating weapon [1] on [Federation Praktor Magister][ID: [truncatedID]56238][34k away]
09:45:21 [Combat] Activating weapon [1] on [Federation Praktor Magister][ID: [truncatedID]56238][34k away]
09:46:40 [Combat] Targeting high value target [Federation Praktor Centurion][ID: [truncatedID]39464][12k away] highValueTargets.Count [3]
09:46:43 [Combat] Activating weapon [1] on [Federation Praktor Magister][ID: [truncatedID]56238][19k away]
09:46:50 [Combat] Activating weapon [1] on [Federation Praktor Magister][ID: [truncatedID]56238][18k away]
09:46:56 [Combat] Activating weapon [1] on [Federation Praktor Magister][ID: [truncatedID]56238][17k away]
09:47:02 [Combat] Activating weapon [1] on [Federation Praktor Magister][ID: [truncatedID]56238][16k away]
09:47:09 [Combat] Activating weapon [1] on [Federation Praktor Magister][ID: [truncatedID]56238][15k away]
09:47:15 [Combat] Activating weapon [1] on [Federation Praktor Magister][ID: [truncatedID]56238][14k away]
09:47:21 [Combat] Activating weapon [1] on [Federation Praktor Magister][ID: [truncatedID]56238][14k away]
09:47:28 [Combat] Activating weapon [1] on [Federation Praktor Magister][ID: [truncatedID]56238][13k away]
09:47:34 [Combat] Activating weapon [1] on [Federation Praktor Magister][ID: [truncatedID]56238][12k away]
09:47:40 [Combat] Activating weapon [1] on [Federation Praktor Magister][ID: [truncatedID]56238][12k away]
09:47:47 [Combat] Activating weapon [1] on [Federation Praktor Magister][ID: [truncatedID]56238][11k away]
09:47:53 [Combat] Activating weapon [1] on [Federation Praktor Magister][ID: [truncatedID]56238][11k away]
09:47:59 [Combat] Activating weapon [1] on [Federation Praktor Magister][ID: [truncatedID]56238][10k away]

**Comment by kn0xv1lle** [comment] 2013-04-08 20:14
Yeah got that issue that he want to activate guns on a target which is not locked.

**Comment by ISeeDEDPpl** [comment] 2013-04-09 13:55
yeah, and I am not sure atm what change caused that =/ 
Ill have to take a closer look tonight. for now revert to experimental until this can be resolved.

**Comment by ISeeDEDPpl** [comment] 2013-04-10 00:27
this looks like a DE bug to me:

public EntityCache GetBestTarget(EntityCache currentTarget, double distance, bool lowValueFirst, string callingroutine)
        {
            // Do we have a 'current target' and if so, is it an actual target?
            // If not, clear current target
            if (currentTarget != null && !currentTarget.IsTarget)
            {
                currentTarget = null;
            }

if the above isn't kicking in when the target is no longer targeted bad things will happen, like questor trying to shoot entities that are not "isTarget" (targeted). 

if so the same issue should be in experimental. this has to be causing some gnarly exceptions in the log server ctrl-alt-shift-m --> log

**Comment by bugc** [comment] 2013-04-15 00:54
hope ISDPPL keeps track of this, because I lost several ships in row just because no tacklers were removed

**Comment by ISeeDEDPpl** [comment] 2013-04-16 17:09
It is a DE bug caused by multiple instances of DE, both stealthed, (one in the login portion and one in questor.) this has been fixed in bleedingedge. please test.

**Comment by ISeeDEDPpl** [comment] 2013-04-18 05:48
bleedingedge is in working order again: please test

**Closed as completed** 2013-04-21 02:38 UTC
