### ISSUE TITLE
panic problem

### ISSUE THREAD

**Issue by xelj** [ISeeDEDPpl/Questor#135] opened 2012-07-02 15:44 UTC
Q dont try warp out in panic until lost ship. Start panic at 22.17.48, but first warp attempt only at 22.20.41
22:17:40 [Drones] Recalling [ 5 ] drones due to shield [78%] below [79%] minimum
22:17:48 [Panic] Start panicking, shield [75%] below [75%] S[75%] A[100%] C[44%] below [15%]
22:17:55 [Drones] Recalling [ 5 ] drones due to shield [68%] below [79%] minimum
22:18:08 [Drones] Recalling [ 5 ] drones due to shield [53%] below [79%] minimum
22:18:22 [Drones] Recalling [ 5 ] drones due to shield [39%] below [79%] minimum
22:18:36 [Drones] Recalling [ 5 ] drones due to shield [22%] below [79%] minimum
22:18:51 [Drones] Recalling [ 5 ] drones due to shield [8%] below [79%] minimum
22:19:07 [Drones] Recalling [ 5 ] drones due to shield [1%] below [79%] minimum
22:19:14 [Questor] Wallet Balance Has Not Changed in [ 2 ] minutes.
22:19:22 [Drones] Recalling [ 5 ] drones due to shield [11%] below [79%] minimum
22:19:39 [Drones] Recalling [ 5 ] drones due to shield [10%] below [79%] minimum
22:19:55 [Drones] Recalling [ 5 ] drones due to shield [10%] below [79%] minimum
22:20:09 [Drones] Recalling [ 5 ] drones due to shield [2%] below [79%] minimum
22:20:15 [Questor] Wallet Balance Has Not Changed in [ 3 ] minutes.
22:20:25 [Drones] Recalling [ 5 ] drones due to shield [0%] below [79%] minimum
22:20:41 [Panic] Warping to [xxxxxxxx]
22:20:41 [Combat] Opening Cargohold of active ship: waiting [3sec]
22:20:41 [CombatMissionCtrl.ClearPocket] Possible out of range. ignoring orbit around structure
22:20:42 [CombatMissionCtrl.ClearPocket] Initiating Orbit [Coreli Guardian Agent][ID: 9000000000000087907]
22:20:42 [Panic] Warping will be attempted again after [4sec]
22:20:43 [Panic] Warping will be attempted again after [3sec]
22:20:45 [Panic] Warping will be attempted again after [2sec]
22:20:46 [Panic] Warping will be attempted again after [1sec]
22:20:46 [Combat] We are jammed and can't target anything

**Comment by ISeeDEDPpl** [comment] 2012-07-10 04:25
Can someone reproduce this issue with current experimental and post another console log? you should be able to replicate it by setting your minimum capacitor to 99% or some such...

**Comment by karope** [comment] 2012-07-11 14:56
I wasn't watching when this happened, but I think the check for being warp scrambled isn't working.  Drones should keep fighting scrambling target while in panic mode.

I am not getting any scramble messages in my questor log.

Here is the log, from the galante mission 'the assault':

17:15:06 [Drones] Recalling [ 5 ] drones due to shield [59%] below [60%] minimum
17:15:07 [Combat] Targeting low value target [Coreli Guardian Initiate][ID:9000000000000256801][15k away] lowValueTargets.Count [0]
17:15:10 [Combat] Activating weapon [1] on [Coreli Guardian Spy][ID: 9000000000000256803][9k away]
17:15:18 [Combat] Activating weapon [1] on [Coreli Guardian Spy][ID: 9000000000000256803][9k away]
17:15:19 [Drones] Engaging [ 5 ] drones on [Coreli Guardian Spy][ID: 9000000000000256803]9k away]
17:15:20 [Drones] Recalling [ 5 ] drones due to shield [60%] below [60%] minimum
17:15:22 [Panic] Start panicking, shield [49%] below [50%] S[49%] A[100%] C[54%] below [15%]
17:15:27 [Combat] Activating weapon [1] on [Coreli Guardian Spy][ID: 9000000000000256803][9k away]
17:15:37 [Combat] Activating weapon [1] on [Coreli Guardian Spy][ID: 9000000000000256803][9k away]
17:15:37 [Drones] Recalling [ 5 ] drones due to shield [46%] below [60%] minimum
17:15:46 [Combat] Activating weapon [1] on [Coreli Guardian Spy][ID: 9000000000000256803][9k away]
17:15:50 [Drones] Recalling [ 5 ] drones due to shield [34%] below [60%] minimum
17:15:54 [Combat] Activating weapon [1] on [Coreli Guardian Spy][ID: 9000000000000256803][9k away]
17:16:03 [Combat] Activating weapon [1] on [Coreli Guardian Spy][ID: 9000000000000256803][9k away]
17:16:09 [Drones] Recalling [ 5 ] drones due to shield [22%] below [60%] minimum
17:16:14 [Combat] Activating weapon [1] on [Coreli Guardian Spy][ID: 9000000000000256803][9k away]
17:16:22 [Drones] Recalling [ 5 ] drones due to shield [13%] below [60%] minimum
17:16:24 [Combat] Activating weapon [1] on [Coreli Guardian Spy][ID: 9000000000000256803][9k away]
17:16:33 [Combat] Activating weapon [1] on [Coreli Guardian Spy][ID: 9000000000000256803][9k away]
17:16:40 [Drones] Recalling [ 5 ] drones due to shield [13%] below [60%] minimum
17:16:43 [Combat] Activating weapon [1] on [Coreli Guardian Spy][ID: 9000000000000256803][9k away]
17:16:52 [Combat] Activating weapon [1] on [Coreli Guardian Spy][ID: 9000000000000256803][9k away]
17:16:54 [Drones] Recalling [ 5 ] drones due to shield [8%] below [60%] minimum
17:17:02 [Combat] Activating weapon [1] on [Coreli Guardian Spy][ID: 9000000000000256803][9k away]
17:17:11 [Combat] Activating weapon [1] on [Coreli Guardian Spy][ID: 9000000000000256803][9k away]
17:17:12 [Drones] Recalling [ 5 ] drones due to shield [14%] below [60%] minimum
17:17:21 [Combat] Activating weapon [1] on [Coreli Guardian Spy][ID: 9000000000000256803][9k away]
17:17:26 [Drones] Recalling [ 5 ] drones due to shield [3%] below [60%] minimum
17:17:29 [Combat] Activating weapon [1] on [Coreli Guardian Spy][ID: 9000000000000256803][9k away]
17:17:40 [Combat] Activating weapon [1] on [Coreli Guardian Spy][ID: 9000000000000256803][9k away]
17:17:41 [Drones] Recalling [ 5 ] drones due to shield [10%] below [60%] minimum
17:17:50 [Combat] Activating weapon [1] on [Coreli Guardian Spy][ID: 9000000000000256803][9k away]
17:17:59 [Combat] Activating weapon [1] on [Coreli Guardian Spy][ID: 9000000000000256803][9k away]
17:18:00 [Drones] Recalling [ 5 ] drones due to shield [0%] below [60%] minimum
17:18:09 [Combat] Activating weapon [1] on [Coreli Guardian Spy][ID: 9000000000000256803][9k away]
17:18:12 [Drones] Recalling [ 5 ] drones due to shield [13%] below [60%] minimum
17:18:20 [Combat] Activating weapon [1] on [Coreli Guardian Spy][ID: 9000000000000256803][9k away]
17:18:37 [Panic] Warping to [Redacted][44.54 AU away]
17:18:37 [Combat] Opening Cargohold of active ship: waiting [4sec]
17:18:38 [CombatMissionCtrl.ClearPocket] Possible out of range. ignoring orbit around structure
17:18:38 [CombatMissionCtrl.ClearPocket] Initiating Orbit [Coreli Guardian Initiate][ID: 9000000000000256802]
17:18:38 [Panic] Warping will be attempted again after [4sec]
17:18:39 [Panic] Warping will be attempted again after [3sec]
17:18:41 [Panic] Warping will be attempted again after [2sec]
17:18:42 [Panic] Warping will be attempted again after [1sec]
17:18:43 [Panic] Warping to [redacted][44.54 AU away]
17:18:43 [Combat] We are jammed and can't target anything
17:18:44 [Panic] Warping will be attempted again after [4sec]
17:18:45 [Panic] Warping will be attempted again after [3sec]
17:19:30 [Panic] We've warped off
17:19:30 [Panic] Approaching to [redacted] which is [2k away]
17:19:31 [Panic] Approaching has been delayed for [-44sec]
17:19:32 [Panic] Approaching has been delayed for [-45sec]
17:19:33 [Panic] Docking with [redacted][0 AU away]
17:19:34 [Panic] Docking will be attempted in [4sec]
17:19:36 [Panic] Docking will be attempted in [3sec]
17:19:37 [Panic] Docking will be attempted in [2sec]
17:19:38 [Panic] Docking will be attempted in [1sec]
17:19:39 [Panic] Docking with [redacted][0 AU away]
17:19:40 [Panic] Docking will be attempted in [4sec]
17:19:41 [Panic] Docking will be attempted in [3sec]
17:19:42 [Panic] Docking will be attempted in [2sec]
17:19:44 [Panic] Entered a station, lower panic mode

**Comment by xelj** [comment] 2012-07-11 15:46
I cant repeat this situation. If it happen again, i try compare logs and give more information

**Comment by tetrikx** [comment] 2012-07-11 21:45
Confirming the problem related to drones and scramblers. I checked my latest logs and I couldnt find any output related to Logging.Log("Drones", "We are scrambled by:... entry even though alot of scrambling took place.

Since apparently questor doesnt detect scramblers (at least not through drones.cs), drones get recalled and depending on char settings they never get launched....this leading to ship loss.

**Comment by ISeeDEDPpl** [comment] 2012-07-12 04:37
well, from what Im hearing the gamelog (ccp generated) doesn't have the scrambled messages in it either. Can you please confirm this? You can test with two toons from the same corp. you shouldn't need to wait until this happens in a mission. Just make sure your testing scenario wont get you concorded. 2 players in the same player corp can aggro each other in highsec without penalty.

**Comment by tetrikx** [comment] 2012-07-12 05:48
I searched eve logs for scrambled messages and they are there:

[ 2012.07.11 17:54:49 ](combat) <color=0xffbb6600>Devilfish Alvi lightly hits you, doing 7.3 damage.
[ 2012.07.11 17:54:49 ](combat) Strain Decimator Alvi misses you completely.
[ 2012.07.11 17:54:49 ](notify) Strain Decimator Alvi has started trying to warp scramble you!
[ 2012.07.11 17:54:50 ](combat) <color=0xffbb6600>Devilfish Alvi places an excellent hit on you, inflicting 14.6 damage.

**Comment by karope** [comment] 2012-07-12 08:38
Hey
Simple solution maybe
Line 289 in drones.cs:
change:
if (warpscrambledby != null && _nextWrapScrambledWarning > DateTime.Now)
to:
if (warpscrambledby != null && _nextWrapScrambledWarning < DateTime.Now)

I still have to do some more testing with it, but the drones will at least stay deployed while scrammed.  I still need to test on a mission if the drones will hit the right target.

**Comment by ISeeDEDPpl** [comment] 2012-07-13 04:04
fixed in current experimental.

**Closed as completed by ISeeDEDPpl** 2012-07-13 04:04 UTC
