### ISSUE TITLE
Regarding drones killing close-orbiting frigs

### ISSUE THREAD

**Issue by Armadillo1** [ISeeDEDPpl/Questor#348] opened 2013-03-03 21:16 UTC
The issue is shown in this picture.
![questorissue](https://f.cloud.github.com/assets/1597809/214779/69a97e14-8447-11e2-8f85-e98be97c2a9d.jpg)

Distance when it should ignore frigs is set to 9000m.

There are 2 frigs left that are aggressing. Questor is trying to finish them off even though they're untrackable with guns. Instead it could just start the new group.

**Comment by Daxten** [comment] 2013-03-03 21:27
that's working as intended, but I also think that could be changed

**Comment by ISeeDEDPpl** [comment] 2013-03-04 07:01
this is now fixed:
https://github.com/ISeeDEDPpl/Questor/commit/21f5bf2a9d3d0c66eba85643c7b69bd4663ca5f7
and
https://github.com/ISeeDEDPpl/Questor/commit/f47a86f80d5be7b1a4d2c8585b9e478dc048902e

**Closed as completed by ISeeDEDPpl** 2013-03-04 07:01 UTC
