### ISSUE TITLE
Resuming after a start in space

### ISSUE THREAD

**Issue by tetrikx** [ISeeDEDPpl/Questor#111] opened 2012-06-12 08:53 UTC
Because of the eve to my location networking issues that happen more and more often lately, Questor is starting more and more often in space. Because of this, I encountered 2 sets of issues:
1. Mission objective completed but required item for mission completion is missing. Questor will send the ship in station and after 3 retries, it will enter in error mode. I dont see any solution to this.
2. This is an issue since a long time ago. 90% of times, after the start in space, mission gets finished but questor gets stuck in idle mode in station even if autostart is true. To reproduce this, quit eve/questor while in different stages of a mission and restart eve/questor.

**Comment by ISeeDEDPpl** [comment] 2012-06-16 06:29
1) can be fixed by having 'extra' required items... or getting lucky and having the required item brought back to base on one ofthe previous partial runs of the mission... 

you can use 
`<trytobring></trytobring>`
and
`<trytobringquantity></trytobringquantity>`
in the root of your mission XML and if the item is available it will bring it during the arm phase... 

2) on the other hand I am not experiencing... I _think_ I know where the issue is though. Ill take a look tomorrow.

**Comment by ISeeDEDPpl** [comment] 2012-06-24 02:58
1. if you can get a console log of this it will be easier to fix...
   you will need to enable two debug logging settings
   `
   <debugAutostart>true</debugAutostart>
   <debugIdle>true<debugIdle>
   `

**Comment by ISeeDEDPpl** [comment] 2012-07-10 04:21
is this still an issue?

**Comment by tetrikx** [comment] 2012-07-10 08:59
Yes, the issue of Idle state not going into DelayedStart after a start in space when Autostart is true is still present but I was using a 6th of july build. I will test today around 6-7pm eve time with the newest build with the debug options turned on and will send you the pastebin logs.

**Comment by tetrikx** [comment] 2012-07-11 21:49
http://pastebin.com/1XussMaj log text message a little bit changed by me...

**Comment by ISeeDEDPpl** [comment] 2012-07-13 04:18
ok, I think Ive found the root cause of this... could you try to reproduce it with latest experimental please?

**Comment by bugc** [comment] 2012-07-22 07:44
I also encounter such an issue using build made before 19-July update (means it is still actual); I'll do attempt to catch it with debug states enabled as you mentioned.

**Closed as completed** 2012-07-26 18:03 UTC
