### ISSUE TITLE
GotoBase not working

### ISSUE THREAD

**Issue by oldmeat** [ISeeDEDPpl/Questor#542] opened 2014-03-06 08:40 UTC
In the latest BE build: https://github.com/ISeeDEDPpl/Questor/commit/70ff53a8bc8369accded8b693a3272efac015da3
When Q start in space, then run DelayedGotoBase and after this Gotobase, but 
not warp to station. Stay in space
http://privatepaste.com/e3cd72b7e7

**Comment by CasualBod** [comment] 2014-03-06 12:58
All is working as intended on previous commit 126289a03a

http://privatepaste.com/8a2120ebea

**Comment by ISeeDEDPpl** [comment] 2014-03-06 13:19
that log of the current build seems awfully short, and no exceptions? very odd...

**Comment by oldmeat** [comment] 2014-03-06 13:22
No exceptions, i have logs from innerspace console too and are the same.

**Comment by ISeeDEDPpl** [comment] 2014-03-06 13:26
can I get a longer, even if repeating log?

**Comment by yomon598** [comment] 2014-03-07 00:02
yes, the latest changes to useInstaBookmark seem to have broken it and, along with it, the traveler.

**Comment by ISeeDEDPpl** [comment] 2014-03-07 00:56
this is highly likely fixed in bleedingedge here: https://github.com/ISeeDEDPpl/Questor/commit/cefb2ae34b6cd8b71de2428a77bf20a7864bf19a
If you have any traveler issues I need a log w `<debugTraveler>true</debugTraveler>`

**Closed as completed** 2014-03-07 01:40 UTC
