### ISSUE TITLE
Unload loot to Freight Container still not work

### ISSUE THREAD

**Issue by oldmeat** [ISeeDEDPpl/Questor#168] opened 2012-08-07 05:38 UTC
Unload loot to Freight Container still not work

**Comment by Chryst** [comment] 2012-08-07 21:13
Sorry in what version ? In the last version ?

**Comment by oldmeat** [comment] 2012-08-08 04:28
I test yesterday the latest build, and in moment when questor open item hangar doesn't open anything

**Comment by Chryst** [comment] 2012-08-08 04:59
Yeah i have just test it and i can confirm it don't work.

**Comment by Chryst** [comment] 2012-08-08 12:35
And first with the old version i was able to fix it, now i'm unable to fix it with the last version so we need wait ise fix it.

**Comment by ISeeDEDPpl** [comment] 2012-08-09 19:06
hrm... I tested it as working fine before I merged in some corp hangar changes from bbday. I'll take another look tonight.

**Comment by Chryst** [comment] 2012-08-10 00:29
Kk thx

**Comment by Chryst** [comment] 2012-08-16 04:21
I have test it again now and it don't open nothing. It get stucked in that point.

And i'm sure my xml is perfect becouse i'm using it with the old version where it was warking.

06:07:51 [AgentInteraction] Attempting to close Agent Window
06:07:53 [AgentInteraction] Done
06:07:54 [CombatMissionsBehavior] UnloadLoot: Begin
06:07:55 [Cache.OpenAmmoHangar] Opening Item Hangar: waiting [4sec]
06:08:00 [UnloadLoot] Moving Ammo to AmmoHangar [('InventorySecondary_StationItems', 60004027)][16672750]
06:08:00 [UnloadLoot] Waiting for items to move to AmmoHangar
06:08:03 [Cache.StackAmmoHangar] Stacking Item Hangar: waiting [3sec]
06:08:04 [UnloadLoot.AmmoHangarStacking] Done stacking AmmoHangar
06:08:05 [Cleanup] CloseInventoryWindows: Closing other Inventory Window named [
('InventorySecondary_ShipCargo_1005794784021', 1005794784021L)]
06:08:07 [Cleanup] CloseInventoryWindows: Closing other Inventory Window named [ ('InventorySecondary_StationItems',
60004027)]
06:08:09 [UnloadLoot] Opening Cargohold of active ship: waiting [4sec]
06:08:13 [Cache.OpenLItemsHangar] Opening Item Hangar: waiting [4sec]
06:08:17 [UnloadLoot] Loot was worth an estimated [63.967] isk in buy-orders
06:08:56 [Questor] Wallet Balance Has Not Changed in [ 2 ] minutes.

**Comment by oldmeat** [comment] 2012-08-16 04:27
Confirm, for me the same

**Comment by Chryst** [comment] 2012-09-01 21:49
Any news on that bug ?

Please, i don't want stress, but is possible fix it ? Are months we ask that.

Thanks

**Comment by ISeeDEDPpl** [comment] 2012-09-02 02:32
the issue is (seemingly) the cache.cs function:

public bool OpenAndSelectInvItem(string module, long ID) 
which is used for both the freight container selection and corp hangar selection in the tree on the left of the inventory window. 

(and)
both:
long ammoHangarID = Cache.Instance.DirectEve.GetCorpHangarId(Settings.Instance.AmmoHangar) - 1;

and 

long lootHangarID = Cache.Instance.DirectEve.GetCorpHangarId(Settings.Instance.LootHangar) - 1;

have never made sense to me. Why does directeve return a value that we have to subtract 1 from before we can pass it back to directeve to select the right tree item?

I didnt write the corp hangar tree selection functions and they dont make logical sence to me so fixing it will have to be handled by someone that can make heads or tails of it. 

I have fully merged in the files bbday linked to me with no changes in behavior. With the above " -1" nonsence I have to wonder if he has it working locally and only locally... like the hangarIDs arent correct for anyone except him. I really dont know. 

It was mentioned by Gannondorf that we might be able to use the hangarName instead of the hangarID but I couldnt work out how to list the hangarNames. There is a directeve function to list the hangarIDs but not an equivalent to list the hangarNames. If their is a way to do this with hangar names instead of IDs I am all ears.

**Comment by Chryst** [comment] 2012-09-03 23:53
bbday have said me DE is unable to open 2 windows same time, so we need first close 1 windows and after ask DE open another. He have said me is that the error in your version. But i dont' know how to fix it.

I really want use your version but with that don't working i can't becouse i use GFC.

If it work i can help a lot in fixing and find bugs. A lot more than now.

**Comment by bbday** [comment] 2012-09-12 22:10
i had fixed in my version.. tomorrow if i finding time i'll fork from isee version and i'll fix a lot of stuff.. and add new functions, new program qstatistic.

**Comment by Chryst** [comment] 2012-09-27 23:40
bbday any news ? Have you try fix the actual ise version ?

**Comment by ISeeDEDPpl** [comment] 2012-10-06 22:46
ok, I spent waaaaaay too much time on this:

https://github.com/ISeeDEDPpl/Questor/tree/InventoryTest
https://github.com/ISeeDEDPpl/Questor/commit/fc72ec831bb363f643c10e6b84c2f5f407c9cd05

I have it working great on a few toons and not working at all on another, but I think that may be limited to that corp having "odd / broken" corp hangars. This needs more testing before we'll really know if its fixed or if we have something else going on that needs attention.  

FYI the comments a month ago were written while testing from the toon that is STILL failing for me, but the other toons in diff corps are working fine so I dunno.

**Comment by Chryst** [comment] 2012-10-09 17:00
It is working perfect now. Running the last version for some hours and seems all perfect.

You can close that issue.

Thx

**Comment by ISeeDEDPpl** [comment] 2012-10-09 21:54
Are you testing LootContainer, AmmoHangar or LootHangar?

I'd like to resolve all of them for this issue to be properly closed. 
I think the last of the issues revolves about the AmmoHangar and LootHangar but not sure exactly what trips them up as it seems sporatic

**Comment by ISeeDEDPpl** [comment] 2012-10-13 10:37
ok, this is now resolved, AmmoHangar, LootHangar, LootContainer, DroneBay, etc no longer require that a window be open thus simplifying everything by a few steps and making the process MUCH less error prone.

**Closed as completed by ISeeDEDPpl** 2012-10-13 10:37 UTC
