### ISSUE TITLE
Client crash

### ISSUE THREAD

**Issue by 1100617** [ISeeDEDPpl/Questor#547] opened 2014-03-13 13:33 UTC
Game client crashes in some quests after this steps, sometimes more than once per quest.

Console Log:
00:00:00 [TargetCombatants]if (Cache.Instance.PreferredPrimaryWeaponTarget != null)
00:00:01 [TargetCombatants]if (Cache.Instance.Entities.Any(i => i.Id == Cache.Instance.PreferredPrimaryWeaponTarget.Id))

Windows Events Log:
Faulting application name: ExeFile.exe, version: 2014.3.74.451
Faulting module name: clr.dll, version: 4.0.30319.18449
Exception code: 0xc00000fd
Faulting application path: _:\_*****_\CCP\EVE\bin\ExeFile.exe
Faulting module path: *:\**_*******\Microsoft.NET\Framework\v4.0.30319\clr.dll

**Comment by ISeeDEDPpl** [comment] 2014-03-13 14:55
odd. how reproducible is this crash?!

see if the logging looks the same in the innerspace log if thats not where you were looking "log wtf.log"
wtf.log will be in the innerspace directory
fyi: the next line, that we dont see in the output just outputs: DirectEntity.Name, DirectEntity.Distance, DirectEntity.HasExploded, DirectEntity.IsTarget, DirectEntity.IsTargeting, EntityCache.IsreadyToTarget (which is just a combination of the previously listed stuff)

**Comment by 1100617** [comment] 2014-03-13 15:05
that's where i looked for.
it's just crashing since last tuesday patch update.
i will try to get more relevant info.

**Comment by ISeeDEDPpl** [comment] 2014-03-14 05:36
it looks like the exceptions you sent via IRC are already fixed in github. you should update your (very old?!?) version of questor

**Closed as completed** 2014-03-15 03:59 UTC
