### ISSUE TITLE
Kill Action

### ISSUE THREAD

**Issue by drokk99** [ISeeDEDPpl/Questor#410] opened 2013-05-30 12:56 UTC
Kill action is not targeting structures for me, using 735d6901b136b8e4ac6389b2e56f0efaff0d39e8
I get

22:25:51 [CombatMissionCtrl] Starting Action.Kill [target: Drone Structure II]
22:25:52 [GetBestTarget: none] Could not determine a suitable target
22:25:53 [GetBestTarget: none] Could not determine a suitable target
22:25:54 [GetBestTarget: none] Could not determine a suitable target

until I manually targeted the structure and then it destroys it

**Comment by drokk99** [comment] 2013-06-12 08:06
Using ed565dc0afaab84f23b5781105309c4231961c16 everything seems to run fine, except for this same problem. Am I the only one getting this, if so it may be something on my end.

**Comment by ISeeDEDPpl** [comment] 2013-06-12 12:18
k, Ill look into this. Its a targeting issue... the target likely needs to be getting passed from the kill action to the targeting routine in combat.cs (targetcombatants) and it looks like that isnt happening, or isnt working right

**Comment by ISeeDEDPpl** [comment] 2013-06-12 12:41
hrm, really looks like that should be working =/ 
Someone will need to enable debugGetBestTarget and debugTargetCombatants and get me a log, please.

**Comment by ISeeDEDPpl** [comment] 2013-06-13 05:34
ok, fixed in bleedingedge. untested. 

re-open with new logs of the _whole pocket_ (or at least 5 min of logs) if the issue is not totally resolved.

**Closed as completed** 2013-06-13 05:35 UTC
